import { describe, it, expect } from 'vitest';
import medicare from './fixtures/drawer-medicare-5day.json';
import texas from './fixtures/drawer-texas-quarterly.json';
import ohio from './fixtures/drawer-ohio-quarterly.json';
import notPriced from './fixtures/drawer-not-priced.json';
import {
  ardBars,
  ardHint,
  capturedOn,
  dayByDate,
  defaultDay,
  displayCode,
  formatAmount,
  formatDelta,
  ntaMeter,
  ntaRows,
  nursingGroups,
  openCount,
  shortDate,
  slpGroups,
  visibleTabs,
  withOverrides,
} from '../lib/drawer-model.js';

// Fixtures are generated by the superapp's own drawer builder
// (core/utils/pdpm-drawer/build-drawer.ts) on synthetic MDS answers.

describe('formatting', () => {
  it('dates are date-only, never shifted by the time zone', () => {
    expect(shortDate('2026-10-04')).toBe('10/4');
    expect(shortDate('2026-01-01')).toBe('1/1');
  });

  it('Medicare in whole dollars, Texas to the cent, CMI to two places', () => {
    expect(formatAmount(medicare.pricing, 747.4)).toBe('$747');
    expect(formatAmount(texas.pricing, 204.42)).toBe('$204.42');
    expect(formatAmount(texas.pricing, 204.42, { compact: true })).toBe('$204');
    expect(formatAmount(ohio.pricing, 1.394)).toBe('1.39');
    expect(formatAmount(notPriced.pricing, 600)).toBe('');
  });

  it('deltas say per day for dollars and nothing for zero', () => {
    expect(formatDelta(medicare.pricing, 142)).toBe('+$142/day');
    expect(formatDelta(texas.pricing, 40.18)).toBe('+$40.18/day');
    expect(formatDelta(ohio.pricing, 0.14)).toBe('+0.14');
    expect(formatDelta(medicare.pricing, 0)).toBe('');
    expect(formatDelta(ohio.pricing, 0.001)).toBe('');
  });

  it('Texas shows its own group code; Medicare shows the HIPPS', () => {
    expect(displayCode(texas.current)).toBe('P3X');
    expect(displayCode(medicare.current)).toBe(medicare.current.hipps);
  });
});

describe('days', () => {
  it('opens on the current ARD', () => {
    expect(defaultDay(medicare)).toBe('2026-10-03');
    expect(dayByDate(medicare, '2026-10-03').isCurrentArd).toBe(true);
  });

  it('an item outside its look-back on a day is not captured that day', () => {
    const iv = medicare.items.find((i) => i.mdsItem === 'O0110H1');
    expect(capturedOn(iv, '2026-09-28')).toBe(false);
    expect(capturedOn(iv, '2026-10-03')).toBe(true);
  });

  it('bars stack review on top of supported and never fall below 45%', () => {
    const bars = ardBars(medicare);
    expect(bars).toHaveLength(7);
    for (const b of bars) {
      expect(b.supportedPct).toBeGreaterThanOrEqual(45);
      expect(b.supportedPct + b.reviewPct).toBeLessThanOrEqual(100.0001);
    }
    // 9/30 carries IV meds + isolation (both review) → the tallest review layer.
    const sep30 = bars.find((b) => b.date === '2026-09-30');
    expect(sep30.reviewPct).toBe(Math.max(...bars.map((b) => b.reviewPct)));
    expect(bars.find((b) => b.isCurrentArd).date).toBe('2026-10-03');
  });

  it('the best-day hint appears only when another day pays more than the current ARD', () => {
    expect(ardHint(medicare)).toBeNull(); // supported is flat across the window
    const hint = ardHint(texas); // IV meds drop out after 10/8; ARD is 10/9
    expect(hint).toEqual({ date: '2026-10-08', delta: '+$40.18' });
  });
});

describe('items and tabs', () => {
  it('Medicare shows Nursing, NTA and SLP; counts leave dismissed items out', () => {
    const tabs = visibleTabs(medicare, medicare.items);
    expect(tabs.map((t) => t.key)).toEqual(['nursing', 'nta', 'slp']);
    const nta = tabs.find((t) => t.key === 'nta');
    expect(nta.total).toBe(4);
    expect(nta.open).toBe(3); // morbid obesity is dismissed
    expect(openCount(medicare.items)).toBe(5);
  });

  it('Texas never shows SLP (it does not pay SLP)', () => {
    expect(visibleTabs(texas, texas.items).map((t) => t.key)).toEqual(['nursing', 'nta']);
  });

  it('Ohio (nursing only) shows only Nursing — diabetes, an NTA item, is not listed', () => {
    expect(visibleTabs(ohio, ohio.items).map((t) => t.key)).toEqual(['nursing']);
    expect(ohio.items.map((i) => i.mdsItem)).toEqual(['O0110M1']);
  });

  it('nursing groups run highest category first; the landing category opens', () => {
    const day = dayByDate(medicare, '2026-09-30');
    const groups = nursingGroups(medicare.items, day);
    expect(groups.map((g) => g.key)).toEqual(['ES', 'SCH', 'CC']);
    expect(groups.find((g) => g.isLanding).key).toBe('ES');
    const later = nursingGroups(medicare.items, dayByDate(medicare, '2026-10-04'));
    expect(later.find((g) => g.isLanding).key).toBe('SCH'); // isolation is out of the window by then
    expect(later.filter((g) => g.defaultOpen).map((g) => g.key)).toEqual(['SCH']);
  });

  it('when nothing lands on the day, the highest category still opens', () => {
    // Texas ARD 10/9: IV meds (the only nursing finding) are outside the look-back.
    const groups = nursingGroups(texas.items, dayByDate(texas, '2026-10-09'));
    expect(groups.some((g) => g.isLanding)).toBe(false);
    expect(groups.filter((g) => g.defaultOpen).map((g) => g.key)).toEqual(['CC']);
  });

  it('NTA rows: most points first, dismissed last', () => {
    const rows = ntaRows(medicare.items);
    expect(rows[0].mdsItem).toBe('O0110H1');
    expect(rows[rows.length - 1].dismissed).toBeTruthy();
  });

  it('SLP rows group by criterion', () => {
    expect(slpGroups(medicare.items).map((g) => g.label)).toEqual(['Swallowing & diet']);
  });

  it('the NTA meter reads coded → with findings on the CMS scale, Groups in Texas', () => {
    const m = ntaMeter(medicare, dayByDate(medicare, '2026-09-30'));
    expect(m.coded).toBe(2);
    expect(m.withReview).toBeGreaterThan(m.supported);
    expect(m.bands.map((b) => b.label)).toContain('NA');
    const t = ntaMeter(texas, dayByDate(texas, '2026-10-05'));
    expect(t.bands.map((b) => b.label)).toEqual(['Group 3', 'Group 2', 'Group 1']);
    expect(t.toBand).toBe('Group 2');
  });

  it('optimistic dismiss / undo overrides the server state until the re-fetch', () => {
    const dm = medicare.items.find((i) => i.mdsItem === 'I2900');
    const after = withOverrides(medicare.items, { [dm.key]: { reason: 'not_given', note: '' } });
    expect(after.find((i) => i.key === dm.key).dismissed.reason).toBe('not_given');
    const obesity = medicare.items.find((i) => i.mdsItem === 'I8000');
    const undone = withOverrides(medicare.items, { [obesity.key]: null });
    expect(undone.find((i) => i.key === obesity.key).dismissed).toBeNull();
  });
});
